Repository cosmos/ethermint, pull requests merged in 2020-11, with the labels that each got.

#590 docs updates
  docs/basics/README.md
  docs/basics/accounts.md
  docs/basics/gas.md
  docs/basics/hard_spoon.md
  docs/basics/json_rpc.md
  docs/basics/transactions.md
  docs/core/README.md
  docs/core/encoding.md
  docs/core/pending_state.md
  docs/intro/README.md
  docs/intro/overview.md
  docs/intro/resources.md
  docs/intro/use_cases.md
Labels: documentation

#603 evm: state transitions enabled params
  CHANGELOG.md
  x/evm/types/errors.go
  x/evm/types/params.go
  x/evm/types/params_test.go
  x/evm/types/state_transition.go
Labels: x/evm

#615 deps: bump cosmos-sdk version to v0.39.2
  CHANGELOG.md
  go.mod
  go.sum
Labels: Status: Needs Review

#614 rpc: fix deadlock
  CHANGELOG.md
  rpc/namespaces/eth/api.go
Labels: Status: Needs Review

#611 update tools configs
  .golangci.yml
  .mergify.yml
  codecov.yml
  tests-solidity/suites/basic/main.go
  utils/int.go
Labels: Status: Needs Review
