Repository cosmos/ethermint, pull requests merged in 2020-09, with the labels that each got.

#496 evm: debug non-determinism
  CHANGELOG.md
  x/evm/types/journal.go
  x/evm/types/journal_test.go
  x/evm/types/statedb.go
Labels: Status: Needs Review

#458 evm: params
  CHANGELOG.md
  Makefile
  app/ante/ante.go
  app/ante/ante_test.go
  app/ante/eth.go
  app/ante/utils_test.go
  app/ethermint.go
  importer/importer_test.go
  tests/rpc_test.go
  x/evm/alias.go
  x/evm/genesis.go
  x/evm/handler.go
  x/evm/keeper/keeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/params.go
  x/evm/keeper/params_test.go
  x/evm/keeper/querier.go
  x/evm/module_test.go
  x/evm/types/chain_config.go
  x/evm/types/chain_config_test.go
  x/evm/types/codec.go
  x/evm/types/errors.go
  x/evm/types/genesis.go
  x/evm/types/genesis_test.go
  x/evm/types/journal_test.go
  x/evm/types/key.go
  x/evm/types/params.go
  x/evm/types/params_test.go
  x/evm/types/state_object.go
  x/evm/types/state_transition.go
  x/evm/types/state_transition_test.go
  x/evm/types/statedb.go
  x/evm/types/statedb_test.go
Labels: Status: Needs Review, x/evm

#499 bump /tests-solidity dependencies
  tests-solidity/yarn.lock
Labels: dependencies

#494 types: update account pubkey JSON to string
  CHANGELOG.md
  crypto/secp256k1.go
  docs/basics/accounts.md
  tests/rpc_test.go
  types/account.go
  types/account_test.go
  types/config_test.go
Labels: Status: Needs Review

#395 deploy network and contract
  .github/workflows/deploy-contract.yml
  .gitignore
  Dockerfile
  Makefile
  go.sum
  init.sh
  scripts/contract-test.sh
  tests-solidity/suites/basic/main.go
Labels: Status: On Ice

#536 docs: ADR template
  docs/architecture/README.md
  docs/architecture/adr-template.md
Labels: Status: Needs Review, documentation

#535 add the rest of the eth methods
  docs/basics/json_rpc.md
Labels: documentation

#542 update chain-id format
  .github/workflows/sims.yml
  CHANGELOG.md
  app/ante/ante_test.go
  app/ante/eth.go
  app/ante/utils_test.go
  client/config.go
  client/testnet.go
  cmd/ethermintcli/main.go
  docs/quickstart/testnet.md
  init.sh
  rpc/eth_api.go
  rpc/net_api.go
  scripts/contract-test.sh
  scripts/integration-test-all.sh
  scripts/run-solidity-tests.sh
  scripts/start.sh
  tests-solidity/README.md
  tests-solidity/init-test-node.sh
  types/chain_id.go
  types/chain_id_test.go
  x/evm/handler.go
  x/evm/handler_test.go
Labels: Status: Needs Review

#552 rpc: implement personal_importRawKey
  CHANGELOG.md
  crypto/algorithm.go
  rpc/apis.go
  rpc/eth_api.go
  rpc/personal_api.go
  tests/personal_test.go
Labels: Status: Needs Review, rpc
