Repository cosmos/ethermint, pull requests merged in 2020-07, with the labels that each got.

#311 docs: vuepress setup and section titles
  .gitignore
  Makefile
  docs/.vuepress/components/Home.vue
  docs/.vuepress/components/IconCode.vue
  docs/.vuepress/components/IconRocket.vue
  docs/.vuepress/components/TmLogoEthereumBlack.vue
  docs/.vuepress/components/TmLogoEthereumWhite.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/logo-bw.svg
  docs/.vuepress/public/logo.svg
  docs/.vuepress/styles/index.styl
  docs/DOCS_README.md
  docs/README.md
  docs/basics/README.md
  docs/basics/accounts.md
  docs/basics/gas.md
  docs/basics/transactions.md
  docs/core/README.md
  docs/core/encoding.md
  docs/core/events.md
  docs/guides/README.md
  docs/guides/img/metamask_import.png
  docs/guides/img/metamask_network_settings.png
  docs/guides/metamask.md
  docs/intro/README.md
  docs/intro/architecture.md
  docs/intro/overview.md
  docs/package-lock.json
  docs/package.json
  docs/post.sh
  docs/pre.sh
  docs/quickstart/README.md
  docs/quickstart/run_node.md
  docs/spec/evm/README.md
  docs/spec/transactions/README.md
  x/evm/spec/README.md
Labels: documentation

#308 rpc: event websocket subscription
  CHANGELOG.md
  go.mod
  go.sum
  rpc/apis.go
  rpc/backend.go
  rpc/eth_api.go
  rpc/filter_api.go
  rpc/filter_system.go
  rpc/filters.go
  rpc/net_api.go
  rpc/types.go
  tests/rpc_test.go
Labels: Status: Needs Review

#361 docs: fixes and websockets guide
  docs/.vuepress/components/Home.vue
  docs/basics/README.md
  docs/basics/accounts.md
  docs/basics/gas.md
  docs/basics/transactions.md
  docs/core/encoding.md
  docs/core/events.md
  docs/package-lock.json
  docs/quickstart/README.md
Labels: Status: Needs Review, documentation

#384 x/evm: journal tests
  x/evm/types/journal.go
  x/evm/types/journal_test.go
Labels: Status: Needs Review

#388 x/evm: state_object tests
  x/evm/types/state_object_test.go
  x/evm/types/statedb_test.go
Labels: Status: Needs Review

#352 evm: fix non-determinism
  tests/rpc_test.go
  types/code.go
  x/evm/genesis.go
  x/evm/genesis_test.go
  x/evm/keeper/querier.go
  x/evm/types/errors.go
  x/evm/types/genesis.go
  x/evm/types/genesis_test.go
  x/evm/types/journal.go
  x/evm/types/journal_test.go
  x/evm/types/state_object.go
  x/evm/types/state_object_test.go
  x/evm/types/statedb.go
  x/evm/types/statedb_test.go
  x/evm/types/storage.go
  x/evm/types/storage_test.go
Labels: Status: Needs Review

#271 Add deploy and call test example to handler_test.go
  x/evm/handler_test.go
Labels: Status: Needs Review, Type: Enhancement, enhancement

#392 x/evm: contract deploy test
  go.mod
  x/evm/handler_test.go
Labels: Status: Needs Review

#393 testnet docs
  .github/workflows/lint.yml
  README.md
  cmd/emintd/main.go
  docs/core/README.md
  docs/core/encoding.md
  docs/core/events.md
  docs/intro/overview.md
  docs/quickstart/README.md
  docs/quickstart/clients.md
  docs/quickstart/events.md
  docs/quickstart/installation.md
  docs/quickstart/run_node.md
  docs/quickstart/testnet.md
  docs/quickstart/upgrade.md
  docs/quickstart/validator-setup.md
Labels: Status: Needs Review, documentation

#407 x/evm: StateBD tests
  .github/workflows/test.yml
  importer/importer_test.go
  tests/rpc_test.go
  x/evm/types/state_object.go
  x/evm/types/statedb.go
  x/evm/types/statedb_test.go
Labels: Status: Needs Review

#378 Local Testnet command
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  cmd/emintcli/keys.go
  cmd/emintd/main.go
  cmd/emintd/testnet.go
  codecov.yml
  crypto/keys.go
  docker-compose.yml
  docs/quickstart/installation.md
  docs/quickstart/run_node.md
  docs/quickstart/testnet.md
  docs/quickstart/validator-setup.md
  networks/local/Makefile
  networks/local/ethermintnode/Dockerfile
  scripts/integration-test-all.sh
  scripts/start.sh
  x/evm/types/state_object.go
Labels: Status: Needs Review, documentation
