Repository cosmos/ethermint, pull requests merged in 2021-01, with the labels that each got.

#670 stargate: migrate types
  CHANGELOG.md
  app/ante/eth.go
  rpc/types/utils.go
  types/types.proto
  types/validation.go
  types/validation_test.go
  x/evm/genesis.go
  x/evm/genesis_test.go
  x/evm/handler.go
  x/evm/keeper/keeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/querier.go
  x/evm/keeper/querier_test.go
  x/evm/keeper/statedb_test.go
  x/evm/types/chain_config.go
  x/evm/types/genesis.go
  x/evm/types/genesis_test.go
  x/evm/types/logs.go
  x/evm/types/logs_test.go
  x/evm/types/msg.go
  x/evm/types/msg_test.go
  x/evm/types/params.go
  x/evm/types/params_test.go
  x/evm/types/querier.go
  x/evm/types/state_object.go
  x/evm/types/state_transition.go
  x/evm/types/statedb.go
  x/evm/types/statedb_test.go
  x/evm/types/storage.go
  x/evm/types/storage_test.go
  x/evm/types/tx_data.go
  x/evm/types/tx_data_test.go
Labels: Status: Needs Review, automerge, x/evm

#679 stargate: proto files
  .clang-format
  Makefile
  buf.yaml
  go.mod
  go.sum
  proto/ethermint/crypto/v1alpha1/ethsecp256k1/keys.proto
  proto/ethermint/evm/v1alpha1/evm.proto
  proto/ethermint/evm/v1alpha1/genesis.proto
  proto/ethermint/evm/v1alpha1/query.proto
  proto/ethermint/evm/v1alpha1/tx.proto
  proto/ethermint/types/v1alpha1/account.proto
  scripts/protoc-swagger-gen.sh
  scripts/protocgen.sh
  third_party/proto/cosmos_proto/cosmos.proto
  third_party/proto/gogoproto/gogo.proto
  third_party/proto/google/api/annotations.proto
  third_party/proto/google/api/http.proto
  third_party/proto/google/api/httpbody.proto
  third_party/proto/google/protobuf/any.proto
  third_party/proto/tendermint/abci/types.proto
  third_party/proto/tendermint/crypto/keys.proto
  third_party/proto/tendermint/crypto/proof.proto
  third_party/proto/tendermint/types/types.proto
Labels: Status: Needs Review

#678 faucet: remove module
  CHANGELOG.md
  app/ethermint.go
  codecov.yml
  docs/guides/join_network.md
  docs/quickstart/run_node.md
  docs/quickstart/testnet.md
  init.sh
  scripts/contract-test.sh
  tests-solidity/init-test-node.sh
  x/faucet/alias.go
  x/faucet/client/cli/query.go
  x/faucet/client/cli/tx.go
  x/faucet/client/rest/tx.go
  x/faucet/genesis.go
  x/faucet/handler.go
  x/faucet/keeper/keeper.go
  x/faucet/keeper/querier.go
  x/faucet/module.go
  x/faucet/types/codec.go
  x/faucet/types/errors.go
  x/faucet/types/events.go
  x/faucet/types/expected_keepers.go
  x/faucet/types/genesis.go
  x/faucet/types/key.go
  x/faucet/types/msgs.go
Labels: Status: Needs Review

#746 add parameter check for evm query func
  CHANGELOG.md
  x/evm/keeper/querier.go
Labels: automerge
